#
# Copyright (c) 2006-2024 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        inject_beef:
            enable: true
            category: "Chrome Extensions"
            name: "Inject BeEF"
            description: "Attempt to inject the BeEF hook on all the available tabs."
            authors: ["Kos", "antisnatchor"]
            target:
                working: ["C"]
                not_working: ["All"]
