#
# Copyright (c) 2006-2024 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        fake_notification:
            enable: true
            category: "Social Engineering"
            name: "Fake Notification Bar"
            description: "Displays a fake notification bar at the top of the screen, similar to those presented in IE."
            authors: ["xntrik"]
            target:
                user_notify: ['ALL']
