#
# Copyright (c) 2006-2024 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        get_page_html:
            enable: true
            category: ["Browser", "Hooked Domain"]
            name: "Get Page HTML"
            description: "This module will retrieve the HTML from the current page."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
