#
# Copyright (c) 2006-2024 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#

#   persist on over app's sleep/wake events
beef:
    module:
        phonegap_persist_resume:
            enable: true
            category: "Phonegap"
            name: "Persist resume"
            description: "Persist over applications sleep/wake events. This module requires the PhoneGap API."
            authors: ["mh"]
            target:
                working: ["All"]
