#
# Copyright (c) 2006-2024 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    extension:
        etag:
            enable: false
            name: 'Server-to-Client Etag Tunnel'
            authors: ["ovbroslavsky", "neoleksov"]
